FROM apache/airflow:3.3.1

USER root

RUN apt-get update \
  && apt-get install -y gcc \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

USER airflow

COPY container_req.txt ./requirements.txt

RUN pip install --no-cache-dir -r requirements.txt