sources:
  - name: walmart_databricks
    database: walmart
    schema: bronze  
    tables:
      - name: customers
      - name: employees
      - name: orders
      - name: order_items
      - name: products
      - name: stores
